#!/usr/bin/env sh
rm -rf public
hugo
cd public
echo "kakaolabs.com" > CNAME
git init
git remote add origin git@github.com:kakaolabs/kakaolabs.github.com.git
git add .
git commit -m 'Deploy'
git push origin master -f
rm -rf public